:rotating_light: Linting and formatting
All files that are `sh` or `bash` are run through shellcheck. All
scripts bangs were changed to use `/usr/bin/env`

List of changed bins:

* git-delete-merged-branches
* +x
* extract
* git-browse
* git-churn
* git-conflicts
* git-credit
* git-deinit
* git-edit
* git-flush
* git-go
* git-maxpack
* git-nuke
* git-rewrite-to-subfolder
* git-shamend
* git-store
* git-sync
* git-up
* git-what-the-hell-just-happened
* git-winner
* macos-wifi

diff --git a/git-go b/git-go
--- a/git-go
+++ b/git-go
@@ -1,30 +1,30 @@
-#!/bin/bash
+#!/usr/bin/env bash
 command -v hub >/dev/null 2>&1 || {
-  echo >&2 "This command needs hub installed and in PATH. http://defunkt.io/hub"
-  exit 1
+    echo >&2 "This command needs hub installed and in PATH. http://defunkt.io/hub"
+    exit 1
 }
 
 # [TODO] make login resolution a function call
 if [ -z "$GITHUB_USER" ]; then
-  echo >&2 "Please define GITHUB_USER with your GitHub user to let me know who you are."
-  exit 1
+    echo >&2 "Please define GITHUB_USER with your GitHub user to let me know who you are."
+    exit 1
 fi
 
 function gh_browse() {
-  open "https://github.com/$1"
+    open "https://github.com/$1"
 }
 
 function repo_browse() {
-  if [ -d .git ]; then
-    hub browse "$1"
-  else
-    echo "Must be in a git repository to run that command."
-    exit 1
-  fi
+    if [ -d .git ]; then
+        hub browse "$1"
+    else
+        echo "Must be in a git repository to run that command."
+        exit 1
+    fi
 }
 
 function usage() {
-  read -r -d '' usage <<"BLOCK"
+    read -r -d '' usage <<"BLOCK"
 USAGE:   git-go [OPTION] [COMMAND]
 
 SYNOPSIS:
@@ -54,23 +54,23 @@ COMMANDS:
         - Everything else forwards to `hub browse`
 BLOCK
 
-  echo "$usage"
+    echo "$usage"
 }
 
 [ $# -eq 0 ] && {
-  usage
-  exit 1
+    usage
+    exit 1
 }
 
 while getopts ":g" opt; do
-  case $opt in
-  g)
-    global_browse=1
-    ;;
-  \?)
-    echo "Invalid option: -$OPTARG" >&2
-    ;;
-  esac
+    case $opt in
+    g)
+        global_browse=1
+        ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        ;;
+    esac
 done
 
 # Clear all options and reset the command line
@@ -78,64 +78,64 @@ shift $((OPTIND - 1))
 
 case "$1" in
 search)
-  gh_browse "search?q=$2"
-  ;;
+    gh_browse "search?q=$2"
+    ;;
 @*)
-  target=$(echo "$1" | sed 's/@//g')
-  gh_browse "$target"
-  ;;
+    target=${1//@/}
+    gh_browse "$target"
+    ;;
 explore)
-  gh_browse 'explore'
-  ;;
+    gh_browse 'explore'
+    ;;
 my*)
-  case $2 in
-  dashboard)
-    gh_browse "dashboard"
-    ;;
-  issues)
-    if [[ -z $global_browse ]]; then
-      case $3 in
-      m*)
-        filter="mentioned"
+    case $2 in
+    dashboard)
+        gh_browse "dashboard"
         ;;
-      c*)
-        filter="created_by"
+    issues)
+        if [[ -z $global_browse ]]; then
+            case $3 in
+            m*)
+                filter="mentioned"
+                ;;
+            c*)
+                filter="created_by"
+                ;;
+            *)
+                filter="assigned"
+                ;;
+            esac
+            repo_browse "-- issues/$filter/$GITHUB_USER"
+        else
+            gh_browse "dashboard/issues"
+        fi
         ;;
-      *)
-        filter="assigned"
+    notifications)
+        if [[ -z $global_browse ]]; then
+            repo_browse "-- notifications/$GITHUB_USER"
+        else
+            gh_browse "dashboard/notifications"
+        fi
         ;;
-      esac
-      repo_browse "-- issues/$filter/$GITHUB_USER"
-    else
-      gh_browse "dashboard/issues"
-    fi
+    profile)
+        gh_browse "$GITHUB_USER"
+        ;;
+    pulls)
+        if [[ -z $global_browse ]]; then
+            repo_browse "-- pulls/$GITHUB_USER"
+        else
+            gh_browse "dashboard/pulls"
+        fi
+        ;;
+    settings)
+        gh_browse "settings/profile"
+        ;;
+    stars)
+        gh_browse "stars"
+        ;;
+    esac
     ;;
-  notifications)
-    if [[ -z $global_browse ]]; then
-      repo_browse "-- notifications/$GITHUB_USER"
-    else
-      gh_browse "dashboard/notifications"
-    fi
-    ;;
-  profile)
-    gh_browse "$GITHUB_USER"
-    ;;
-  pulls)
-    if [[ -z $global_browse ]]; then
-      repo_browse "-- pulls/$GITHUB_USER"
-    else
-      gh_browse "dashboard/pulls"
-    fi
-    ;;
-  settings)
-    gh_browse "settings/profile"
-    ;;
-  stars)
-    gh_browse "stars"
-    ;;
-  esac
-  ;;
 *)
-  repo_browse "-- $1"
-  ;;
+    repo_browse "-- $1"
+    ;;
 esac
diff --git a/git-shamend b/git-shamend
--- a/git-shamend
+++ b/git-shamend
@@ -27,13 +27,13 @@ set -o nounset
 # THE SOFTWARE.
 
 PrintGitShamendUsage() {
-  echo "Usage: git shamend [options] [<revision>]"
-  echo "Amends your staged changes as a fixup (keeping the pre-existing commit"
-  echo "message) to the specified commit, or HEAD if no revision is specified."
-  echo
-  echo "Options:"
-  echo "    -a, --all             Commit unchanged files, same as git commit."
-  echo "    -h, --help            Print this help."
+    echo "Usage: git shamend [options] [<revision>]"
+    echo "Amends your staged changes as a fixup (keeping the pre-existing commit"
+    echo "message) to the specified commit, or HEAD if no revision is specified."
+    echo
+    echo "Options:"
+    echo "    -a, --all             Commit unchanged files, same as git commit."
+    echo "    -h, --help            Print this help."
 }
 
 ALL=""
@@ -41,78 +41,75 @@ SHA_TO_AMEND=""
 
 # parse arguments
 while [ "$#" -gt 0 ]; do
-  case $1 in
+    case $1 in
     -h | --help)
-      PrintGitShamendUsage
-      exit 0
-      ;;
+        PrintGitShamendUsage
+        exit 0
+        ;;
     -a | --all)
-      ALL="--all"
-      ;;
+        ALL="--all"
+        ;;
     *)
-      if [ -n "$SHA_TO_AMEND" ]; then
-        echo "ERROR: unknown parameter \"$1\""
-        PrintGitShamendUsage
-        exit 1
-      fi
-      SHA_TO_AMEND=$(git rev-parse "$1")
-      if [ ! $? ]; then
-        echo "ERROR: unparsable revision \"$1\""
-        PrintGitShamendUsage
-        exit 1
-      fi
-      ;;
-  esac
-  shift
+        if [ -n "$SHA_TO_AMEND" ]; then
+            echo "ERROR: unknown parameter \"$1\""
+            PrintGitShamendUsage
+            exit 1
+        fi
+        SHA_TO_AMEND=$(git rev-parse "$1")
+        if [ ! $? ]; then
+            echo "ERROR: unparsable revision \"$1\""
+            PrintGitShamendUsage
+            exit 1
+        fi
+        ;;
+    esac
+    shift
 done
 
 # fall back to HEAD if no SHA was given
 if [ -z "$SHA_TO_AMEND" ]; then
-  SHA_TO_AMEND="HEAD"
+    SHA_TO_AMEND="HEAD"
 fi
 
 # shortcut the HEAD case for simplicity
 if [ "$SHA_TO_AMEND" = "HEAD" ]; then
-  git commit --amend --no-edit $ALL
-  exit 0
+    git commit --amend --no-edit $ALL
+    exit 0
 fi
 
 BOLD=$(tput bold)
 RED=$(tput setaf 1)
 NORMAL=$(tput sgr0)
 
-if git merge-base --is-ancestor $SHA_TO_AMEND HEAD
-then
+if git merge-base --is-ancestor $SHA_TO_AMEND HEAD; then
 
-  if [ -z "$ALL" ]; then
-    echo "${BOLD}Warning: your unstaged changes will be stashed during this process${NORMAL}"
-  fi
+    if [ -z "$ALL" ]; then
+        echo "${BOLD}Warning: your unstaged changes will be stashed during this process${NORMAL}"
+    fi
 
-  git commit $ALL --fixup $SHA_TO_AMEND > /dev/null
+    git commit $ALL --fixup $SHA_TO_AMEND >/dev/null
 
-  git diff-index --quiet HEAD
-  NOTHING_TO_STASH=$?
-  if [ $NOTHING_TO_STASH -ne 0 ]
-  then
-    git stash > /dev/null
-  fi
+    git diff-index --quiet HEAD
+    NOTHING_TO_STASH=$?
+    if [ $NOTHING_TO_STASH -ne 0 ]; then
+        git stash >/dev/null
+    fi
 
-  GIT_EDITOR=true git rebase -i --autosquash "$SHA_TO_AMEND^"
+    GIT_EDITOR=true git rebase -i --autosquash "$SHA_TO_AMEND^"
+    REBASE_EXIT=$?
 
-  if [ $? -ne 0 ]
-  then
-    git rebase --abort
-    git reset --soft HEAD^
-    echo "${RED}${BOLD}Whoops, that didn't work! Cleaning up after this attempt now, but"
-    echo "it looks like you'll have to interactive rebase this one manually.${NORMAL}"
-  fi
+    if [ ${REBASE_EXIT} -ne 0 ]; then
+        git rebase --abort
+        git reset --soft HEAD^
+        echo "${RED}${BOLD}Whoops, that didn't work! Cleaning up after this attempt now, but"
+        echo "it looks like you'll have to interactive rebase this one manually.${NORMAL}"
+    fi
 
-  if [ $NOTHING_TO_STASH -ne 0 ]
-  then
-    git stash pop > /dev/null
-  fi
+    if [ $NOTHING_TO_STASH -ne 0 ]; then
+        git stash pop >/dev/null
+    fi
 else
-  echo "${RED}${BOLD}${SHA_TO_AMEND} is not an ancestor of HEAD.${NORMAL}"
-  PrintGitShamendUsage
-  exit 1
+    echo "${RED}${BOLD}${SHA_TO_AMEND} is not an ancestor of HEAD.${NORMAL}"
+    PrintGitShamendUsage
+    exit 1
 fi
diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -14,18 +14,17 @@
 #
 function sync_branch() {
     local current_branch_name remote branch_name all_remotes
-    all_remotes=$(git remote)
+    all_remotes=("$(git remote)")
     current_branch_name=$(git rev-parse --abbrev-ref HEAD)
-    remotes=(${1:-origin})
+    remotes=("${1:-origin}")
     if [[ $1 == "all" ]]; then
-        remotes=$all_remotes
+        remotes=("${all_remotes[@]}")
     fi
     branch_name=${2:-${current_branch_name}}
-    for remote in $remotes; do
-        echo "==== Syncing ${branch_name} -> ${remote}/${branch_name}"
-        git pull --rebase ${remote} ${branch_name} && (git push ${remote} ${branch_name} && echo "==== Synced ${branch_name} -> ${remote}/${branch_name} sucessfully" || echo "==== Error when pushing changes to ${remote}/${branch_name}") || echo "==== Error when fetching changes from ${remote}/${branch_name}"
+    for remote in "${remotes[@]}"; do
+        echo "=== Syncing ${branch_name} -> ${remote}/${branch_name}"
+        git pull --rebase "${remote}" "${branch_name}" && (git push "${remote}" "${branch_name}" && echo "=== Synced ${branch_name} -> ${remote}/${branch_name} sucessfully" || echo "=== Error when pushing changes to ${remote}/${branch_name}") || echo "=== Error when fetching changes from ${remote}/${branch_name}"
     done
 }
 
 sync_branch "$@"
-
